services:
  rethinkdb:
    build: .
    container_name: rethink-lab
    ports:
      - "8080:8080" 
      - "28015:28015"
    volumes:
      - ./rethink-data:/data:z
  flight_producer:
    build: 
      context: ./flight_producer
    user: root
    depends_on:
      - rethinkdb
    environment:
      DB_HOST: rethinkdb
      PYTHONUNBUFFERED: 1
      OPEN_SKY_CLIENT_ID: ${CLIENT_ID}
      OPEN_SKY_CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - ./flight_producer/credentials.json:/app/credentials.json:ro
  flight_map:
    build:
      context: ./flight_map
    depends_on:
      - rethinkdb
    environment:
      DB_HOST: rethinkdb
    ports:
      - "5000:5000"