services:
  rethinkdb:
    build: .
    container_name: rethink-lab
    ports:
      - "8080:8080" 
      - "28015:28015"
    volumes:
      - ./rethink-data:/data:z
  flight_producer:
      build: 
        context: ./flight_producer
      depends_on:
        - rethinkdb
      environment:
        DB_HOST: rethinkdb
        PYTHONUNBUFFERED: 1
  flight_map:
    build:
      context: ./flight_map
    depends_on:
      - rethinkdb
    environment:
      DB_HOST: rethinkdb
    ports:
      - "5000:5000"